### PR TITLE
Fix blank menu after selecting heatmap

### LINKED ISSUE #706: Symbology panel: blank menu after selecting heatmap
### JupyterGIS version

0.5.0

### Description

Image

Repro:

1. Load `earthquakes.jGIS`
2. Set to heatmap symbology, leave everything default
3. Click OK
4. Everything looks fine
5. Re-open symbology menu
6. Looks like above!

### PR DESCRIPTION
**Pull request by arjxn-py**
## Description

Resolves #706 

## Checklist

- [ ] PR has a descriptive title and content.
- [ ] PR description contains [references](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to any issues the PR resolves, e.g. `Resolves #XXX`.
- [ ] PR has one of the labels: documentation, bug, enhancement, feature, maintenance
- [ ] Checks are passing.
      Failing lint checks can be resolved with:
  - `pre-commit run --all-files`
  - `jlpm run lint`

---
📚 Documentation preview: https://jupytergis--707.org.readthedocs.build/en/707/
💡 JupyterLite preview: https://jupytergis--707.org.readthedocs.build/en/707/lite

### CODE REVIEW

File: packages/base/src/dialogs/symbology/vector_layer/VectorRendering.tsx [hunk 1]
```diff
@@ -37,7 +37,8 @@ const VectorRendering = ({
 
     const options: Record<string, string[]> = {
       VectorLayer: ['Single Symbol', 'Graduated', 'Categorized', 'Heatmap'],
-      VectorTileLayer: ['Single Symbol']
+      VectorTileLayer: ['Single Symbol'],
+      HeatmapLayer: ['Heatmap']
```
Comment (martinRenou) [inline packages/base/src/dialogs/symbology/vector_layer/VectorRendering.tsx:41]: Shouldn't this be:

```suggestion
      HeatmapLayer: ['Single Symbol', 'Graduated', 'Categorized', 'Heatmap']
```

Otherwise it seems we can't go back to a "single symbol" after setting heatmap rendering:


https://github.com/user-attachments/assets/855e69c9-b1c9-44ad-a274-16d611fef7c6

Comment (arjxn-py) [reply packages/base/src/dialogs/symbology/vector_layer/VectorRendering.tsx:41]: Ahh yes, you're right.
I didn't test for this case, thank you for taking care of this.

**Comment by arjxn-py** [comment]
I still see a small issue while going back to single symbol rendering. looking into it

File: packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx [hunk 2]
```diff
@@ -171,7 +171,9 @@ const Graduated = ({
 
     layer.parameters.symbologyState = symbologyState;
     layer.parameters.color = newStyle;
-    layer.type = 'VectorLayer';
+    if (layer.type === 'HeatmapLayer') {
+      layer.type = 'VectorLayer';
```
Comment (martinRenou) [inline packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx:175]: That explains the `layer.type` assignment we used to have 👍🏽

**Review by martinRenou — APPROVED** [review]
Neat! Thanks!

File: packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx (hunk 2 above)
Comment (arjxn-py) [reply packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx:175]: Yes, one concern remains though that this is not ideal if we apply heatmapLayer to any other type than `VectorLayer` for example `VectorTileLayer` will fail like before if we enable heatmaplayer symbology on it. We'd need to find a better solution.

However it's not concerning as of now since we apply heatmaplayer to `VectorLayer` currently.
