### PR TITLE
Fix SingleBand pseudocolor band selector bug, index bands from 1

### LINKED ISSUE #958: Singleband pseudocolor band selector doesn't respect user selection
### JupyterGIS version

_No response_

### Description

E.g. when the user selects "Band 2", it immediately resets to "Band 1". It's always 1 less. It happens about 90% of the time, I'd say?

Image

### LINKED ISSUE #1063: Singleband pseudocolor band selector doesn't respect user selection
### JupyterGIS version

main

### Description

When you select a band on the singleband pseudocolor symbology menu, the dropdown changes it to the -1 band immediately after.

Image

### PR DESCRIPTION
**Pull request by nakul-py**
## Description

Resolves #1063 

Fixing SingleBand pseudocolor band selector bug by separating hooks into `useGetSingleBandInfo` and `useGetMultiBandInfo`. The idea of separation of `useGetBandInfo` arise in https://github.com/geojupyter/jupytergis/pull/912#discussion_r2421048339 

- Closes #958 

cc @mfisher87 @martinRenou 
## Checklist

- [x] PR has a descriptive title and content.
- [x] PR description contains [references](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to any issues the PR resolves, e.g. `Resolves #XXX`.
- [x] PR has one of the labels: documentation, bug, enhancement, feature, maintenance
- [x] Checks are passing.
      Failing lint checks can be resolved with:
  - `pre-commit run --all-files`
  - `jlpm run lint`

---
📚 Documentation preview: https://jupytergis--998.org.readthedocs.build/en/998/
💡 JupyterLite preview: https://jupytergis--998.org.readthedocs.build/en/998/lite

### CODE REVIEW

File: packages/base/src/dialogs/symbology/hooks/useGetSingleBandInfo.ts [hunk 1]
```diff
@@ -67,19 +58,20 @@ const useGetBandInfo = (model: IJupyterGISModel, layer: IJGISLayer) => {
       const image = await tiff.getImage();
       const numberOfBands = image.getSamplesPerPixel();
 
+      const bands: ISingleBandRow[] = [];
       for (let i = 0; i < numberOfBands; i++) {
-        bandsArr.push({
-          band: i,
+        bands.push({
+          band: i + 1,
```
Comment (mfisher87) [inline packages/base/src/dialogs/symbology/hooks/useGetSingleBandInfo.ts:65]: This is the core of the fix, right? Are the rest of the changes necessary to fix this bug? Apologies, I've forgotten some of the context around this issue :)

Comment (nakul-py) [reply packages/base/src/dialogs/symbology/hooks/useGetSingleBandInfo.ts:65]: Yes this is the core fix. Rest of changes is also necessary because if we fix only in the `useGetBandInfo` so the Singleband bug teleport to Multiband because we are using common hook in both useGetBandInfo. More info here https://github.com/geojupyter/jupytergis/pull/912#discussion_r2421048339

File: packages/base/src/dialogs/symbology/hooks/useGetSingleBandInfo.ts [hunk 2]
```diff
@@ -20,23 +13,21 @@ export interface IBandRow {
...
     setError(null);
 
     try {
-      const bandsArr: IBandRow[] = [];
       const source = model.getSource(layer?.parameters?.source);
       const sourceInfo = source?.parameters?.urls[0];
 
       if (!sourceInfo?.url) {
         setError('No source URL found.');
-        setLoading(false);
```
Comment (mfisher87) [inline packages/base/src/dialogs/symbology/hooks/useGetSingleBandInfo.ts:39]: Let's restore this line, we still want to set loading to false once we've completed this step and return.

**Comment by mfisher87** [comment]
@nakul-py and I worked on this together today. There were two things we wanted to address:

1) Can this PR be more targeted? I.e. fix the strange dropdown behavior without a refactor. We noticed that the singleband pseudocolor component expected bands to be 1-indexed, and the multiband component expected them to be 0-indexed, so we could make this bug "teleport" between components by changing the useGetBandInfo hook from 0-indexed to 1-indexed.
2) Bug: This PR changes singleband to be 1-indexed, but multiband is still 0-indexed. In the `main` branch, both are 0-indexed.

We worked together to produce an alternate changeset: https://github.com/geojupyter/jupytergis/compare/main...mfisher87:jupytergis:singleband-dropdown-fix

This changeset changes:
* Bands are always be 1-indexed, mirroring behavior of GDAL and QGIS, so it should be more familiar to users.
* Fixes the dropdown-changing bug on the multiband component (the bug "teleports" there from the singleband component when we move to 1-indexing). I tested it against the `main` branch jupyterlite deployment and the visual results are the same after correcting for band numbers (i.e. multiband red=0 green=1 blue=2 in `main` looks the same as multiband red=1 green=2 blue=3 in the new changeset).
* Removes a bit of dead code, like this PR currently does

@nakul-py what do you think? Do you want to update this PR to use our new changeset?

### Idea for a refactor

Currently we're doing a bunch of `+1` `-1` stuff that I'd like to not do. What if we changed the bandrows array so that the 0th entry represents "Unset" and bump all the other rows so their array index matches their band number? `0` is currently used to represent "unset" in the code already. We would just need to hide that option in the singleband component and show it in the multiband component.
