### PR TITLE
Form refactor

### LINKED ISSUE #1118: Adding new layers behaves strangely in general, throws errors for GeoTiffs
### JupyterGIS version

0.13.1

### Description

Tested on the ReadTheDocs deployment and locally with same behavior. I tried recording a demo, but had some problems. Linux life 🙄 

Reproduction:

1) New project
2) Add a vector tile layer. Do not click OK!
3) Vector tile layer present in layers panel 😲 
4) Click "cancel" 
5) Vector tile layer still present

Or

1) Add GeoTIFF layer
2) GeoTIFF layer present in layers panel 😲 
3) Click browse
4) Error: `Error Adding Custom GeoTiff Layer. Failed to add Custom GeoTiff Layer: Invalid file format for tiff content.`
5) Click OK
6) See bugged file browser
7) Click cancel
8) Click browse
9) See working file browser
10) Select a GeoTIFF
11) Click OK
12) A second GeoTIFF layer is added to the layers panel
13) Only the 2nd GeoTIFF has data.

Project file below. Note that the VectorTile and GeoTIFF layers have no source information.

```json
{
  "layerTree": [
    "da049453-a4a2-4978-9094-f18ba264ebf4",
    "5caeb03e-d416-4930-86b4-48dfde79afa3",
    "dea6a6ef-2741-45e5-9f92-4746e9220268"
  ],
  "layers": {
    "5caeb03e-d416-4930-86b4-48dfde79afa3": {
      "name": "Custom GeoTiff Layer",
      "parameters": {
        "opacity": 1.0,
        "source": "1bd41376-3841-4eeb-9a3a-ed6a0eaa95d1",
        "symbologyState": {
          "alphaBand": 4.0,
          "band": 1.0,
          "blueBand": 3.0,
          "colorRamp": "viridis",
          "greenBand": 2.0,
          "interpolation": "linear",
          "mode": "equal interval",
          "nClasses": "9",
          "redBand": 1.0,
          "renderType": "Single Symbol"
        }
      },
      "type": "WebGlLayer",
      "visible": true
    },
    "da049453-a4a2-4978-9094-f18ba264ebf4": {
      "name": "Custom Vector Tile Layer",
      "parameters": {
        "color": {},
        "opacity": 1.0,
        "source": "b37ddc4f-43e7-4349-a69f-3c6217bbe4e0",
        "symbologyState": {}
      },
      "type": "VectorTileLayer",
      "visible": true
    },
    "dea6a6ef-2741-45e5-9f92-4746e9220268": {
      "name": "Custom GeoTiff Layer",
      "parameters": {
        "opacity": 1.0,
        "source": "1c6e7374-4dd6-4c22-bc96-3d56cf790929",
        "symbologyState": {
          "alphaBand": 4.0,
          "band": 1.0,
          "blueBand": 3.0,
          "colorRamp": "viridis",
          "greenBand": 2.0,
          "interpolation": "linear",
          "mode": "equal interval",
          "nClasses": "9",
          "redBand": 1.0,
          "renderType": "Single Symbol"
        }
      },
      "type": "WebGlLayer",
      "visible": true
    }
  },
  "metadata": {},
  "options": {
    "bearing": 0.0,
    "extent": [
      -20037508.34278924,
      -10998461.038975678,
      20037508.34278924,
      10998461.038975678
    ],
    "latitude": 0.0,
    "longitude": 0.0,
    "pitch": 0.0,
    "projection": "EPSG:3857",
    "zoom": 2.4522412404308187
  },
  "schemaVersion": "0.5.0",
  "sources": {
    "1bd41376-3841-4eeb-9a3a-ed6a0eaa95d1": {
      "name": "Custom GeoTiff Source",
      "parameters": {
        "interpolate": false,
        "normalize": true,
        "urls": [
          {}
        ],
        "wrapX": false
      },
      "type": "GeoTiffSource"
    },
    "1c6e7374-4dd6-4c22-bc96-3d56cf790929": {
      "name": "Custom GeoTiff Source",
      "parameters": {
        "interpolate": false,
        "normalize": true,
        "urls": [
          {}
        ],
        "wrapX": false
      },
      "type": "GeoTiffSource"
    },
    "b37ddc4f-43e7-4349-a69f-3c6217bbe4e0": {
      "name": "Custom Vector Tile Layer Source",
      "parameters": {
        "attribution": "",
        "maxZoom": 24.0,
        "minZoom": 0.0,
        "provider": "",
        "url": "",
        "urlParameters": {}
      },
      "type": "VectorTileSource"
    }
  },
  "stories": {}
}
```

Video by @martinRenou 

https://github.com/user-attachments/assets/c3cac22a-a21d-4f17-9876-350c313151e8

### PR DESCRIPTION
**Pull request by gjmooney**
## Description

Fix #1118 

The old form layer used a class hierarchy, the `BaseForm` held the schema, state, and RJSF wiring, and each layer or source type extended it (or a subclass like `LayerPropertiesForm` or `PathBasedSourcePropertiesForm`) and overrode `processSchema`, `onFormChange`, and `onFormSubmit`. That meant a lot of indirect behavior, when sync ran and when validation ran depended on `formContext` and `isInitialLoadRef` and other stuff buried in the base class. It wasn't always clear who owned what, the form kept schema and form data inside it, and callers (`CreationForm`, `EditForm`, dialogs) had to coordinate through props, signals, and promises instead of one clear contract.

The refactor switched to composition. `SchemaForm` is just one primitive component, it renders a schema-driven form and reports changes. It doesn't own persistence, create/update mode, or dialog behavior. The caller owns state and decides what to do on change and submit. Shared logic lives in functions in `schemaUtils`. Type-specific forms call those instead of extending a base class. Each layer or source type is one functional component in its own file. It keeps `formData` in local state, builds `schema` and `uiSchema` with `schemaUtils` plus whatever that type needs, and renders `SchemaForm` with clear `onChange` and `onSubmit`. The same component is used for create and edit contexts, `formContext` only controls which fields show up or are read-only. `CreationForm` and `EditForm` still get the same props (`schema`, `sourceData`, `syncData`, `model`, `formContext`, etc.) and still use formselectors to pick the right form by type. Only the implementation of each type form changed (from class to function plus the `SchemaForm`), so the rest of the app (dialogs, properties panel) stays the same. So now it's easier to add or change a layer or source form (one file, no subclass chain), we can see when data syncs because it's in each component's handlers, and we can test or reuse `SchemaForm` on its own.

TODO:

- [ ] Re-add `--fail-on-warning` to docs build script

## Checklist

- [x] PR has a descriptive title and content.
- [x] PR description contains [references](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to any issues the PR resolves, e.g. `Resolves #XXX`.
- [x] PR has one of the labels: documentation, bug, enhancement, feature, maintenance
- [ ] Checks are passing.
      Failing lint checks can be resolved with:
  - `pre-commit run --all-files`
  - `jlpm run lint`
- [x] If you wish to be cited for your contribution, `CITATION.cff` contains an [author entry](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionsperson) for yourself

---
📚 Documentation preview: https://jupytergis--1147.org.readthedocs.build/en/1147/
💡 JupyterLite preview: https://jupytergis--1147.org.readthedocs.build/en/1147/lite
💡 Specta preview: https://jupytergis--1147.org.readthedocs.build/en/1147/lite/specta

### CODE REVIEW

**Comment by martinRenou** [comment]
Thanks @gjmooney ! Can you please remove the "fail-on-warning" entry here https://github.com/geojupyter/jupytergis/blob/42afa3446de7d5c0812bd1e8d3ac9d8d72822984/docs/build.sh#L11 for now? So that the docs build passes

File: docs/build.sh [hunk 1]
```diff
@@ -8,7 +8,7 @@ ${THIS_DIR}/clean.sh
 
 python -m sphinx \
     --nitpicky --show-traceback \
-    --fail-on-warning --keep-going \
+    --keep-going \
```
Comment (mfisher87) [inline docs/build.sh:11]: We need to re-add this 😬

Comment (mfisher87) [reply docs/build.sh:11]: Docs police :rotating_light: :police_officer: :oncoming_police_car: :rotating_light: woop woop it's the [sound of da police](https://www.youtube.com/watch?v=9ZrAYxWPN6c)

Comment (nakul-py) [reply docs/build.sh:11]: 😂😂
